# -*- coding: utf-8 -*-
"""Caleb Penley A6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iRaoO8wBwKXrp3ImxNGMNoY6V_IwAyLO
"""

# Comments
def uneven_valley(N):
  if N <= 0:
    return
  if N % 2 == 0:
    print(N - 2)
    uneven_valley(N - 2)
    print(N - 1)
  else:
    print(N-1)
    uneven_valley(N - 1)
    print(N)
def multiple(N):
  if N == 1:
    return N
  else:
    product = N * multiple(N-1)
  return product
def valleymultiple(N, M):
  if (N == M):
    return M
  product = N * valleymultiple(N + 1, M) * N
  return product
def sumitup(N):
  if (N == 0):
    return N
  sum = N + sumitup(N - 1)
  return sum
def print_hill(N, M):
  if (N == M):
    print(M, end=",")
    return
  print(N, end=",")
  print_hill(N + 1, M)
  if N != 1:
    print(N, end=",")
  else:
    print(N, end=" ")

def main():
  ### Your Code Goes Here -- starting with indentation (lines up)
  uneven_valley(6)
  test = multiple(5)
  print(test)
  test = valleymultiple(1, 5)
  print(test)
  test = sumitup(5)
  print(test)
  print_hill(1, 5)

if __name__ == '__main__':
    main()