# -*- coding: utf-8 -*-
"""E4_Caleb_Penley.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f51kwKk185hFSnvCz52JK5pXagI1mFKt
"""

def find_min(lst):
  if len(lst) == 0:
    return -1
  min_value = lst[0]
  min_index = 0
  for i in range(len(lst)):
    if lst[i] < min_value:
      min_value = lst[i]
      min_index = i
  result = []
  result += [min_value]
  result += [min_index]
  return result

def reverse_lst(lst):
  rev_lst = []
  for i in range(len(lst)):
    rev_lst += [(lst[len(lst)-1-i])]
  return rev_lst

def index_in_list(lst,x):
  for i in range(len(lst)):
    if lst[i] == x:
      return i
  return -1

def index_ops(lst):
  new_lst = []
  for i in range(len(lst)):
    if i % 2 == 0:
      new_lst += [lst[i] * 2]
    else:
      new_lst += [lst[i] * 3]
  return new_lst

def grade_it(lst):
  grades = []
  for i in range(len(lst)):
    if lst[i] >= 80 and lst[i] <= 100:
      grades += ['A']
    elif lst[i] >= 50 and lst[i] <= 79:
      grades += ['B']
    elif lst[i] >= 0 and lst[i] <= 49:
      grades += ['C']
    else:
      grades += ['I']
  return grades
def main():
  test = find_min([8,4,2,3,1])
  print(test)
  test = reverse_lst([1,2,3,4,5])
  print(test)
  test = index_in_list([1,2,3,4,5], 4)
  print(test)
  test = index_ops([2,3,4,7,9,4])
  print(test)
  test = grade_it([-1,67,101,13,97,43])
  print(test)
if __name__ == '__main__':
    main()