# -*- coding: utf-8 -*-
"""T2_Penley_Caleb_cjp6402.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JCpjeYTU6i201DiKQWkTjwn8hZVO-S2d
"""

#1
def reverse_lst(lst):
  rev_lst = []
  for i in range(len(lst)):
    rev_lst += [(lst[len(lst)-1-i])]
  return rev_lst

#2
def index_in_list(lst,x):
  for i in range(len(lst)):
    if lst[i] == x:
      return i
  return -1

#3
def index_ops(lst):
  new_lst = []
  for i in range(len(lst)):
    if i % 2 == 0:
      new_lst += [lst[i] * 2]
    else:
      new_lst += [lst[i] * 3]
  return new_lst